# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QHBoxLayout

import asyncio
from prisma import Prisma

from Weather.Weather import *


from functions import *

API="734f075ec68072c87b588cff622658f0"
BASE_URL= "https://api.openweathermap.org/data/2.5/weather?"



class Ui_MainWindow(object):

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(794, 518)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
                self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 611))
                self.tabWidget.setStyleSheet("QWidget#widget{\n"
        "background-color:qlineargradient(spread:pad, x1:0.944, y1:0.909, x2:0.346, y2:0.226, stop:0 rgba(41, 9, 21, 255), stop:1 rgba(97, 0, 112, 255))\n"
        "}")
        
                self.tabWidget.setObjectName("tabWidget")
                self.tab = QtWidgets.QWidget()
                self.tab.setObjectName("tab")
                self.cityComboBox = QtWidgets.QComboBox(self.tab)
                self.cityComboBox.setGeometry(QtCore.QRect(440, 230, 281, 22))
                self.cityComboBox.setObjectName("cityComboBox")
                self.cityComboBox.insertItem(0,"PLEASE SELECT CITY")
                self.cityComboBox.addItems(["Adana","Adiyaman","Afyon","Agri","Aksaray","Amasya","Ankara","Antalya","Ardahan","Artvin","Aydin","Balikesir","Bartin","Batman","Bayburt","Bilecik","Bingol","Bitlis","Bolu","Burdur","Bursa","Canakkale","Cankiri","Corum","Denizli","Diyarbakir","Duzce","Edirne","Elazig","Erzincan","Erzurum","Eskisehir","Gaziantep","Giresun","Gumushane","Hakkari","Hatay","Igdir","Isparta","Istanbul","Izmir","Kahramanmaras","Karabuk","Karaman","Kars","Kastamonu","Kayseri","Kilis","Kirikkale","Kirklareli","Kirsehir","Kocaeli","Konya","Kutahya","Malatya","Manisa","Mardin","Mersin","Mugla","Mus","Nevsehir","Nigde","Ordu","Osmaniye","Rize","Sakarya","Samsun","Sanliurfa","Siirt","Sinop","Sirnak","Sivas","Tekirdag","Tokat","Trabzon","Tunceli","Usak","Van","Yalova","Yozgat","Zonguldak"])
                self.showButton = QtWidgets.QPushButton(self.tab)
                self.showButton.setGeometry(QtCore.QRect(320, 280, 131, 41))
                self.showButton.setStyleSheet("color:white;\n"
        "background-color:rgb(98, 98, 98);")
                self.showButton.setObjectName("showButton")
                self.genderComboBox = QtWidgets.QComboBox(self.tab)
                self.genderComboBox.setGeometry(QtCore.QRect(70, 230, 251, 22))
                self.genderComboBox.setObjectName("genderComboBox")
                self.genderComboBox.insertItem(0,"PLEASE SELECT GENDER")
                self.genderComboBox.addItem("MALE")
                self.genderComboBox.addItem("FEMALE")
                self.label = QtWidgets.QLabel(self.tab)
                self.label.setGeometry(QtCore.QRect(70, 190, 141, 21))
                self.label.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
        "color:white;")
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.tab)
                self.label_2.setGeometry(QtCore.QRect(450, 190, 141, 21))
                self.label_2.setStyleSheet("font: 75 20pt \"MS Shell Dlg 2\";\n"
        "color:white;")
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.tab)
                self.label_3.setGeometry(QtCore.QRect(260, 10, 241, 81))
                self.label_3.setStyleSheet("font: 75 38pt \"MS Shell Dlg 2\";\n"
        "color:white;\n"
        "")
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.tab)
                self.label_4.setGeometry(QtCore.QRect(260, 90, 241, 21))
                self.label_4.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";\n"
        "color:white;")
                self.label_4.setObjectName("label_4")
                self.label_5 = QtWidgets.QLabel(self.tab)
                self.label_5.setGeometry(QtCore.QRect(70, 350, 241, 20))
                self.label_5.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";\n"
        "color:white;")
                self.label_5.setObjectName("label_5")
                self.widget_2 = QtWidgets.QWidget(self.tab)
                self.widget_2.setGeometry(QtCore.QRect(0, 0, 801, 481))
                self.widget_2.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.944, y1:0.909, x2:0.346, y2:0.226, stop:0 rgba(41, 9, 21, 255), stop:1 rgba(97, 0, 112, 255))\n"
        "")
                self.widget_2.setObjectName("widget_2")
                self.combinationLabel = QtWidgets.QLabel(self.widget_2)
                self.combinationLabel.setGeometry(QtCore.QRect(0, 390, 791, 121))
                self.combinationLabel.setStyleSheet("color:white;\n"
        "font: 75 20pt \"MS Shell Dlg 2\";")
                self.combinationLabel.setText("")
                self.combinationLabel.setObjectName("combinationLabel")
                self.label_16 = QtWidgets.QLabel(self.widget_2)
                self.label_16.setGeometry(QtCore.QRect(480, 350, 81, 20))
                self.label_16.setStyleSheet("\n"
        "font: 75 11pt \"MS Shell Dlg 2\";\n"
        "color:white;\n"
        "")
                self.label_16.setObjectName("label_16")
                self.weatherLabel = QtWidgets.QLabel(self.widget_2)
                self.weatherLabel.setEnabled(True)
                self.weatherLabel.setGeometry(QtCore.QRect(560, 340, 131, 51))
                self.weatherLabel.setStyleSheet("QWidget#widget{\n"
        "}")
                self.weatherLabel.setText("")
                self.weatherLabel.setObjectName("weatherLabel")
                self.widget_2.raise_()
                self.cityComboBox.raise_()
                self.showButton.raise_()
                self.genderComboBox.raise_()
                self.label.raise_()
                self.label_2.raise_()
                self.label_3.raise_()
                self.label_4.raise_()
                self.label_5.raise_()
                self.tabWidget.addTab(self.tab, "")
                self.tab_2 = QtWidgets.QWidget()
                self.tab_2.setObjectName("tab_2")
                self.label_7 = QtWidgets.QLabel(self.tab_2)
                self.label_7.setGeometry(QtCore.QRect(270, 80, 321, 21))
                self.label_7.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";\n"
        "color:white;")
                self.label_7.setObjectName("label_7")
                self.label_8 = QtWidgets.QLabel(self.tab_2)
                self.label_8.setGeometry(QtCore.QRect(220, 150, 321, 21))
                self.label_8.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
        "color:white;")
                self.label_8.setObjectName("label_8")
                self.label_9 = QtWidgets.QLabel(self.tab_2)
                self.label_9.setGeometry(QtCore.QRect(70, 200, 81, 21))
                self.label_9.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";\n"
        "color:white;")
                self.label_9.setObjectName("label_9")
                self.genderDataComboBox = QtWidgets.QComboBox(self.tab_2)
                self.genderDataComboBox.setGeometry(QtCore.QRect(70, 230, 251, 22))
                self.genderDataComboBox.setObjectName("genderDataComboBox")
                self.genderDataComboBox.insertItem(0,"PLEASE SELECT GENDER")
                self.genderDataComboBox.addItem("MALE")
                self.genderDataComboBox.addItem("FEMALE")
                self.label_10 = QtWidgets.QLabel(self.tab_2)
                self.label_10.setGeometry(QtCore.QRect(490, 200, 91, 21))
                self.label_10.setStyleSheet("font: 75 15pt \"MS Shell Dlg 2\";\n"
        "color:white;")
                self.label_10.setObjectName("label_10")
                self.weatherComboBox = QtWidgets.QComboBox(self.tab_2)
                self.weatherComboBox.setGeometry(QtCore.QRect(490, 230, 251, 22))
                self.weatherComboBox.setObjectName("weatherComboBox")
                self.weatherComboBox.insertItem(0,"PLEASE SELECT WEATHER CONDITION")
                self.weatherComboBox.addItems(["SUNNY" , "CLOUDY","RAINY","SNOWY"])
                self.label_11 = QtWidgets.QLabel(self.tab_2)
                self.label_11.setGeometry(QtCore.QRect(200, 320, 81, 16))
                self.label_11.setStyleSheet("color:white;")
                self.label_11.setObjectName("label_11")
                self.label_12 = QtWidgets.QLabel(self.tab_2)
                self.label_12.setGeometry(QtCore.QRect(230, 350, 41, 16))
                self.label_12.setStyleSheet("color:white;")
                self.label_12.setObjectName("label_12")
                self.label_13 = QtWidgets.QLabel(self.tab_2)
                self.label_13.setGeometry(QtCore.QRect(220, 380, 51, 16))
                self.label_13.setStyleSheet("color:white;")
                self.label_13.setObjectName("label_13")
                self.label_14 = QtWidgets.QLabel(self.tab_2)
                self.label_14.setGeometry(QtCore.QRect(230, 410, 47, 13))
                self.label_14.setStyleSheet("color:white;")
                self.label_14.setObjectName("label_14")
                self.saveButton = QtWidgets.QPushButton(self.tab_2)
                self.saveButton.setGeometry(QtCore.QRect(290, 450, 171, 23))
                self.saveButton.setStyleSheet("color:white;\n"
        "background-color:rgb(98, 98, 98)\n"
        "")
                self.saveButton.setObjectName("saveButton")
                self.widget = QtWidgets.QWidget(self.tab_2)
                self.widget.setGeometry(QtCore.QRect(0, -10, 801, 591))
                self.widget.setObjectName("widget")
                self.label_6 = QtWidgets.QLabel(self.widget)
                self.label_6.setGeometry(QtCore.QRect(270, 10, 241, 81))
                self.label_6.setStyleSheet("font: 75 38pt \"MS Shell Dlg 2\";\n"
        "color:white;")
                self.label_6.setObjectName("label_6")
                self.outherwearLineEdit = QtWidgets.QLineEdit(self.widget)
                self.outherwearLineEdit.setGeometry(QtCore.QRect(300, 330, 161, 20))
                self.outherwearLineEdit.setObjectName("outherwearLineEdit")
                self.topsLineEdit = QtWidgets.QLineEdit(self.widget)
                self.topsLineEdit.setGeometry(QtCore.QRect(300, 360, 161, 20))
                self.topsLineEdit.setObjectName("topsLineEdit")
                self.bottomsLineEdit = QtWidgets.QLineEdit(self.widget)
                self.bottomsLineEdit.setGeometry(QtCore.QRect(300, 390, 161, 20))
                self.bottomsLineEdit.setObjectName("bottomsLineEdit")
                self.shoesLineEdit = QtWidgets.QLineEdit(self.widget)
                self.shoesLineEdit.setGeometry(QtCore.QRect(300, 420, 161, 20))
                self.shoesLineEdit.setObjectName("shoesLineEdit")
                self.widget.raise_()
                self.label_7.raise_()
                self.label_8.raise_()
                self.label_9.raise_()
                self.genderDataComboBox.raise_()
                self.label_10.raise_()
                self.weatherComboBox.raise_()
                self.label_11.raise_()
                self.label_12.raise_()
                self.label_13.raise_()
                self.label_14.raise_()
                self.saveButton.raise_()
                self.tabWidget.addTab(self.tab_2, "")
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                self.tabWidget.setCurrentIndex(1)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.showButton.setText(_translate("MainWindow", "SHOW COMBINATIONS"))
                self.label.setText(_translate("MainWindow", "GENDER"))
                self.label_2.setText(_translate("MainWindow", "CITY"))
                self.label_3.setText(_translate("MainWindow", "WELCOME"))
                self.label_4.setText(_translate("MainWindow", "DRESS COMBINATION APP"))
                self.label_5.setText(_translate("MainWindow", "SUGGESTIONS FOR THE WEATHER"))
                self.label_16.setText(_translate("MainWindow", "WEATHER:"))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "USER SCREEN"))
                self.label_7.setText(_translate("MainWindow", "DRESS COMBINATION APP"))
                self.label_8.setText(_translate("MainWindow", "FOR DATA ENTRY SPECIALIST"))
                self.label_9.setText(_translate("MainWindow", "GENDER"))
                self.label_10.setText(_translate("MainWindow", "WEATHER"))
                self.label_11.setText(_translate("MainWindow", "OUTHERWEAR:"))
                self.label_12.setText(_translate("MainWindow", "TOPS:"))
                self.label_13.setText(_translate("MainWindow", "BOTTOMS:"))
                self.label_14.setText(_translate("MainWindow", "SHOES:"))
                self.saveButton.setText(_translate("MainWindow", "SAVE COMBINATION"))
                self.label_6.setText(_translate("MainWindow", "WELCOME"))
                self.outherwearLineEdit.setPlaceholderText(_translate("MainWindow", "Coat,Jacket etc."))
                self.topsLineEdit.setPlaceholderText(_translate("MainWindow", "Sweatshirt ,T-shirt, Crop etc."))
                self.bottomsLineEdit.setPlaceholderText(_translate("MainWindow", "Skirt,Pants,Leggigs etc."))
                self.shoesLineEdit.setPlaceholderText(_translate("MainWindow", "Sneakers,High heels etc."))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "DATA ENTRY"))

                self.saveButton.clicked.connect(self.clickE)
                self.showButton.clicked.connect(self.take_weather)
        

        def take_weather(self):
                        city =self.cityComboBox.currentText()
                        sicak = a_b(city)
                        desc = a_c(city)
                        
                        self.weatherLabel.setText("  Temp :  " + "{:.0f}".format((float(sicak) - 273.15)) + "\n" + "  Description : " + str(desc))
                        self.combinationLabel.setText("OUTHERWEAR: " + "\nTOPS: "  +  "\nBOTTOMS: " )
         
        def clickE(self) -> None:

                outherwear=self.outherwearLineEdit.text()
                tops=self.topsLineEdit.text()
                bottoms=self.bottomsLineEdit.text()
                shoes=self.shoesLineEdit.text()
                currentWeather = self.weatherComboBox.currentText()
                currentGender = self.genderDataComboBox.currentText()

                self.setGender(currentGender)
                if __name__ == '__main__':
                        asyncio.run(data_transfer(currentGender, currentWeather, tops , outherwear, bottoms, shoes))

        



class MyClass():
        async def data_transfer() -> None:
                data = Ui_MainWindow()
                data.getGender()
                print("My Gender: "+ data.getGender())

        



        
        

        

Uygulama = QApplication(sys.argv)
winMain=QMainWindow()
ui=Ui_MainWindow()
ui.setupUi(winMain)
winMain.show()
sys.exit(Uygulama.exec_())


